# Generated by Django 3.0.2 on 2020-12-21 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200, null=True)),
                ('Email', models.EmailField(max_length=254)),
                ('Address', models.CharField(max_length=200, null=True)),
                ('Address2', models.CharField(max_length=200, null=True)),
                ('Country', models.CharField(max_length=200, null=True)),
                ('state', models.CharField(max_length=200, null=True)),
                ('Zip', models.CharField(max_length=200, null=True)),
                ('Shipping_Address', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Home.Products'),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='discount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(default='/Koala.jpg/', upload_to=''),
        ),
        migrations.AlterField(
            model_name='products',
            name='profile_pic',
            field=models.ImageField(blank=True, default='/Koala.jpg/', null=True, upload_to=''),
        ),
    ]
