# Generated by Django 3.0.2 on 2020-12-26 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_auto_20201221_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='Country',
            field=models.CharField(choices=[('I', 'India'), ('G', 'Ghana')], max_length=200, null=True),
        ),
    ]
