# Generated by Django 3.0.2 on 2021-01-03 10:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_auto_20201226_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='ontent',
            field=models.FileField(default=django.utils.timezone.now, upload_to='images'),
            preserve_default=False,
        ),
    ]
