# Generated by Django 3.0.2 on 2021-01-03 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_customer_ontent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='ontent',
            new_name='content',
        ),
    ]
