# Generated by Django 3.0.2 on 2021-01-03 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_auto_20210103_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='content',
            field=models.FileField(upload_to=''),
        ),
    ]
