# Generated by Django 3.0.2 on 2021-01-07 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Home', '0007_auto_20210103_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='Name',
        ),
        migrations.AddField(
            model_name='checkout',
            name='user',
            field=models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Home.Checkout'),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='Country',
            field=django_countries.fields.CountryField(default=django.utils.timezone.now, max_length=746, multiple=True),
            preserve_default=False,
        ),
    ]
