# Generated by Django 3.0.2 on 2021-01-08 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_auto_20210107_1726'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='billing_address',
            new_name='Billing_address',
        ),
    ]
