# Generated by Django 3.0.2 on 2021-01-08 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_auto_20210108_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Billing_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Home.Checkout'),
        ),
    ]
