# Generated by Django 3.0.2 on 2021-01-09 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_auto_20210108_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='Payment_options',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
